---
- hosts: all
  gather_facts: false
  tasks:
    - name: Wait for SSH
      wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 300
      vars:
        ansible_user: ec2-user
- hosts: all
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
  - name: Install Docker
    yum: 
      name: docker
      state: latest
  - name: Start Docker
    service:
      name: docker
      state: started
      enabled: yes
  - name: Modify User
    user:
      name: ec2-user
      groups: docker
      append: yes
  - name: Install docker-compose
    pip:
      name: docker-compose>1.7.0,<2.0.0
      executable: pip3
  - name: make directory
    file:
      path: /home/ec2-user/hello2048
      state: directory
      mode: '0755'
      owner: ec2-user
      group: ec2-user
  - name: Download docker-compose.yml
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/qebyn/hello-terraform/ansible-docker/docker/docker-compose.yml
      dest: /home/ec2-user/hello2048
      owner: ec2-user
      group: ec2-user
  - name: Pull and run images
    community.docker.docker_compose:
      project_src: /home/ec2-user/hello2048
      pull: true
    vars:
      ansible_python_interpreter: /usr/bin/python3
